/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "cap_des2.h"
/* Header for class com_example_chengmengzhen_securitykeybroad_jninative_JniEncode */

#ifndef _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#define _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_encryption
  (JNIEnv *, jobject, jbyteArray);

JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_decryption
        (JNIEnv *, jobject, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
