/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <stdio.h>
#include <jni.h>

#include<android/log.h>
#define LOG_TAG    "JNILOG" // 这个是自定义的LOG的标识
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG, __VA_ARGS__)
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG, __VA_ARGS__)
#define LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG, __VA_ARGS__)
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG, __VA_ARGS__)
#define LOGF(...)  __android_log_print(ANDROID_LOG_FATAL,LOG_TAG, __VA_ARGS__)
//#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

#include "cap_des2.h"
/* Header for class com_example_chengmengzhen_securitykeybroad_jninative_JniEncode */

#ifndef _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#define _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_encryption
        (JNIEnv *env, jobject obj, jbyteArray pwd) {
    LOGE("########## i = %d", 1);
//
//    int len = (*env)->GetArrayLength(env,pwd);
//    char * bytes =(char *)malloc(len+1);
//    (*env)->GetByteArrayRegion(env,pwd,0,len,bytes);
//    jbyteArray newjbyte = (*env)->NewByteArray(env,len);
//    jbyte* pJbyte = (*env)->GetByteArrayElements(env,newjbyte,0);
//    int i ;
//    for (i = 0; i <len ; ++i) {
//        pJbyte[i]= bytes[i];
//    }
    //jbyte*      (*GetByteArrayElements)(JNIEnv*, jbyteArray, jboolean*);
    //把jstring转成char ＊
//    int len = (*env)->GetStringLength(env, pwd);
//    char *cpwd = (char *) malloc(len + 1);
//    (*env)->GetStringUTFRegion(env, pwd, 0, len, cpwd);

    LOGE("########## i = %d", 2);
    //1 . 找到java代码的 class文件
    ///Users/chengmengzhen/AndroidStudioProjects/SecurityKeyBroad/app/src/main/java/.java
    jclass clazz = (*env)->FindClass(env, "com/example/chengmengzhen/securitykeybroad/utils/DESCoding");
    if(clazz == NULL){

        LOGE("find class error");

    }
    jmethodID method4 = (*env)->GetStaticMethodID(env, clazz, "encode","([B)Ljava/lang/String;");
    if(method4== NULL){

        LOGE("find method error");

    }
//    LOGE("%s",clazz);
//    LOGE("%s",method4);
    LOGE("########## i = %d", 3);
//    jobject     (*CallObjectMethod)(JNIEnv*, jobject, jmethodID, ...);
    //(*env)->CallVoidMethod(env, obj, method4);
    LOGE("########## i = %d", 4);
    //free(bytes);
    return (jstring)(*env)->CallStaticObjectMethod(env, clazz, method4,pwd);
    //(*env)->CallVoidMethod(env,obj,method4);
    //return  NULL;
//     ((*env)->CallObjectMethod(env,obj,method4,newjbyte));
    LOGE("########## i = %d", 5);


}

JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_decryption
        (JNIEnv *env, jobject obj, jbyteArray pwd) {


}

#ifdef __cplusplus
}
#endif
#endif
