/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <stdio.h>
#include <jni.h>

#include<android/log.h>
#define LOG_TAG    "JNILOG" // 这个是自定义的LOG的标识
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG, __VA_ARGS__)
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG, __VA_ARGS__)
#define LOGW(...)  __android_log_print(ANDROID_LOG_WARN,LOG_TAG, __VA_ARGS__)
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG, __VA_ARGS__)
#define LOGF(...)  __android_log_print(ANDROID_LOG_FATAL,LOG_TAG, __VA_ARGS__)
//#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

/* Header for class com_example_chengmengzhen_securitykeybroad_jninative_JniEncode */

#ifndef _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#define _Included_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chengmengzhen_securitykeybroad_jninative_JniEncode
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_encryption
        (JNIEnv *env, jobject obj, jbyteArray pwd) {

    //1 . 找到java代码的 class文件
    ///Users/chengmengzhen/AndroidStudioProjects/SecurityKeyBroad/app/src/main/java/.java
    jclass clazz = (*env)->FindClass(env, "com/example/chengmengzhen/securitykeybroad/utils/DESCoding");
    if(clazz == NULL){
        LOGE("find class error");
    }
    jmethodID method4 = (*env)->GetStaticMethodID(env, clazz, "encode","([B)Ljava/lang/String;");
    if(method4== NULL){
        LOGE("find method error");
    }

    return (jstring)(*env)->CallStaticObjectMethod(env, clazz, method4,pwd);
}

JNIEXPORT jstring JNICALL Java_com_example_chengmengzhen_securitykeybroad_jninative_JniEncode_decryption
        (JNIEnv *env, jobject obj, jbyteArray pwd) {


}

#ifdef __cplusplus
}
#endif
#endif
